### ISSUE TITLE
Call-ID

### ISSUE THREAD

**Issue by ben-rowe** [kirm/sip.js#76]
Hello All,

Having an issue with 'Call-ID' rather than 'call-id'. although i can send the invite i don't receive a response in node. I have managed to confirm that the responses are making to my computer but they are not being parsed or seen in node.

I am using the example sip invite from the repo.

Any ideas?

Many Thanks
Ben

**Comment by kirm** [comment]
I can't say anything without actually looking at messages.

**Comment by ben-rowe** [comment]
I've masked the ip addresses that are public as well as the phone numbers involved. I am expecting the 603 unauthorized but still do not see any of the responses arriving in node. When i send the invite with a lower case call-id i have no issues, only when Call-ID is capitalized.

=== Sent from Node ===
INVITE sip:0123456789@0.0.0.0;trans-type=5 SIP/2.0
To:  <sip:0123456789@0.0.0.0>
From:  <sip:0123456789@0.0.0.0>;tag=410510
Call-ID: 580817
CSeq: 1 INVITE
content-type: application/sdp
Contact:  <sip:101@O1AVs-MacBook-Pro.local>
Via: SIP/2.0/UDP O1AVs-MacBook-Pro.local:5060;branch=z9hG4bK626184;rport

== Sent From kamailio ==
SIP/2.0 100 Trying
To:  <sip:0123456789@0.0.0.0>
From:  <sip:0123456789@0.0.0.0>;tag=410510
Call-ID: 580817
CSeq: 1 INVITE
Via: SIP/2.0/UDP O1AVs-MacBook-Pro.local:5060;branch=z9hG4bK626184;rport=5060;received=0.0.0.0
Server: kamailio (4.2.4 (x86_64/linux))
Content-Length: 0

== Sent From kamailio ==
SIP/2.0 603 Unauthorized! Go Away!
To:  <sip:0123456789@0.0.0.0>;tag=f2b7ab957195cd36ceb4811eea1b2fca.1e36
From:  <sip:0123456789@0.0.0.0>;tag=410510
CSeq: 1 INVITE
Via: SIP/2.0/UDP O1AVs-MacBook-Pro.local:5060;branch=z9hG4bK626184;rport=5060;received=0.0.0.0
Call-ID: 580817
Server: kamailio (4.2.4 (x86_64/linux))
Content-Length: 0

**Comment by kirm** [comment]
sip.js doesn't seem to have any issues parsing these messages, and transaction ids extracted from them match. So it is likely some kind of problem with transport.
Have you enabled logs to be sure sip.js did not receive these messages?

**Comment by ben-rowe** [comment]
Yes i have i only see send debug messages, no receive messages. Wireshark shows the packets reaching my machine though. It is worth running i am running node 10 not node 12 i will try it in node 12 later today.

DEBUG: send
{ method: 'INVITE',
  uri: 'sip:0123456789@0.0.0.0;trans-type=5',
  headers: 
   { to: { uri: 'sip:0123456789@0.0.0.0' },
     from: { uri: 'sip:0123456789@0.0.0.0', params: { tag: '785388' } },
     'Call-ID': '780552',
     cseq: { method: 'INVITE', seq: 1 },
     'content-type': 'application/sdp',
     contact: [ { uri: 'sip:101@O1AVs-MacBook-Pro.local' } ],
     content: '',
     via: 
      [ { params: { branch: 'z9hG4bK309058', rport: null },
          host: 'O1AVs-MacBook-Pro.local',
          port: 5060,
          protocol: 'UDP' } ],
     'content-length': 0 } }

**Comment by ben-rowe** [comment]
Running in version 12 makes no difference.

**Comment by kirm** [comment]
Maybe packets arrive on interface sip.js isn't listening on? Try to set address propery in options object you supply to sip.start to address of the interface packets arrive.

**Comment by ben-rowe** [comment]
Ok getting there, i now see sip.js getting the response debug messages. However i do not receive anything in the call back of the invite and just keeps retrying. Any Ideas? Thanks for all your help so far.

DEBUG: send
{ method: 'INVITE',
  uri: 'sip:0123456789@0.0.0.0;trans-type=5',
  headers: 
   { to: { uri: 'sip:0123456789@0.0.0.0' },
     from: { uri: 'sip:0123456789@0.0.0.0', params: { tag: '321830' } },
     'Call-ID': '829661',
     cseq: { method: 'INVITE', seq: 1 },
     'content-type': 'application/sdp',
     contact: [ { uri: 'sip:101@O1AVs-MacBook-Pro.local' } ],
     content: '',
     via: 
      [ { params: { branch: 'z9hG4bK300242', rport: null },
          host: 'O1AVs-MacBook-Pro.local',
          port: 5060,
          protocol: 'UDP' } ],
     'content-length': 0 } }
util.debug: Use console.error instead
DEBUG: recv
{ version: '2.0',
  status: 100,
  reason: 'Trying',
  headers: 
   { to: 
      { name: undefined,
        uri: 'sip:0123456789@0.0.0.0',
        params: {} },
     from: 
      { name: undefined,
        uri: 'sip:0123456789@0.0.0.0',
        params: { tag: '321830' } },
     'call-id': '829661',
     cseq: { seq: 1, method: 'INVITE' },
     via: 
      [ { version: '2.0',
          protocol: 'UDP',
          host: 'O1AVs-MacBook-Pro.local',
          port: 5060,
          params: 
           { branch: 'z9hG4bK300242',
             rport: '5060',
             received: '0.0.0.0' } } ],
     server: 'kamailio (4.2.4 (x86_64/linux))',
     'content-length': 0 },
  content: '' }
util.debug: Use console.error instead
DEBUG: recv
{ version: '2.0',
  status: 603,
  reason: 'Unauthorized! Go Away!',
  headers: 
   { to: 
      { name: undefined,
        uri: 'sip:0123456789@0.0.0.0',
        params: { tag: 'f2b7ab957195cd36ceb4811eea1b2fca.6890' } },
     from: 
      { name: undefined,
        uri: 'sip:0123456789@0.0.0.0',
        params: { tag: '321830' } },
     'call-id': '829661',
     cseq: { seq: 1, method: 'INVITE' },
     via: 
      [ { version: '2.0',
          protocol: 'UDP',
          host: 'O1AVs-MacBook-Pro.local',
          port: 5060,
          params: 
           { branch: 'z9hG4bK300242',
             rport: '5060',
             received: '0.0.0.0' } } ],
     server: 'kamailio (4.2.4 (x86_64/linux))',
     'content-length': 0 },
  content: '' }

**Comment by kirm** [comment]
Can you also enable error log?

**Comment by ben-rowe** [comment]
Tried enabling the error log i see no changes in the output.

**Comment by kirm** [comment]
Can you show me actual code and log?

**Comment by luminblade** [comment]
I'm having this same problem.  If I set the 'call-id' header, my vendor complains.  If I set the 'Call-ID' header, my vendor works correctly, but sip.js does not map the 302 response correctly to my callback (it does receive it).  If I set both 'call-id' and 'Call-ID' headers, everyone is happy (except me, since that is ugly).

**Comment by luminblade** [comment]
It appears that createInviteClientTransaction is not normalizing the 'Call-ID' head to 'call-id', and then failing to find the transaction via getClient() in exports.create.

**Comment by ben-rowe** [comment]
Please see this Gist this is code and a full output log i have truncated the log as it just keeps looping.

https://gist.github.com/ben-rowe/f70f15e25b611e607a82

**Comment by kirm** [comment]
The right name for Call-ID header in sip.js parsed messages is 'call-id' regardless of actual name ('call-id', 'Call-ID', 'i', 'cAlL-iD') in message. Since commit a216e8890c1b9b4652519e1bd431edc4f189cf41 the name for the header in stringified message is always 'Call-ID'. It seems that commit haven't made it npm package yet. Could you please check if it fixes the issue.

**Comment by ben-rowe** [comment]
Hey, have tested it unfortunately still exactly the same response. Many Thanks, Ben

**Comment by kirm** [comment]
Did you change 'Call-ID' to 'call-id' on line 48 in your code?

**Comment by ben-rowe** [comment]
call-id has always worked, Call-ID is something i have to send to the third party service.

**Comment by kirm** [comment]
sip.js does not support header with name 'Call-ID' in parsed structure. It needs the header to be named 'call-id'. When it stringifies message to send it over network it expands 'call-id' in parsed message to 'Call-ID'.

**Comment by luminblade** [comment]
sip.js is not standardizing 'call-id' to 'Call-ID' on outbound call invites.  The make_call.js example exhibits this problem, run it as is, capture the packets and you will see 'call-id' as a header, which is not recognized and rejected by many sip providers since it is not standard.

Here's the output of "sipgrep -h lo" for my test.

node make_call.js sip:1001@127.0.0.1:5060

U 2015/04/22 13:45:56.018881 127.0.0.1:5060 -> 127.0.0.1:5060
INVITE sip:1001@127.0.0.1:5060 SIP/2.0.
To:  <sip:1001@127.0.0.1:5060>.
From:  <sip:test@test>;tag=649721.
call-id: 790289.
CSeq: 36999 INVITE.
content-type: application/sdp.
Contact:  <sip:101@d1ds04.telepointglobal.com>.
Via: SIP/2.0/UDP d1ds04.telepointglobal.com:5060;branch=z9hG4bK845546;rport.
content-length: 220.
.
v=0.
o=- 13374 13374 IN IP4 127.0.01.
s=-.
c=IN IP4 127.0.01.
t=0 0.
m=audio 16424 RTP/AVP 0 8 101.
a=rtpmap:0 PCMU/8000.
a=rtpmap:8 PCMA/8000.
a=rtpmap:101 telephone-event/8000.
a=fmtp:101 0-15.
a=ptime:30.
a=sendrecv.


U 2015/04/22 13:45:56.028402 127.0.0.1:5060 -> 127.0.0.1:5060
SIP/2.0 405 Method not allowed.
Via: SIP/2.0/UDP d1ds04.telepointglobal.com:5060;branch=z9hG4bK845546;rport=5060;received=127.0.0.1.
To:  <sip:1001@127.0.0.1:5060>.
From:  <sip:test@test>;tag=649721.
call-id: 790289.
CSeq: 36999 INVITE.
.


U 2015/04/22 13:45:56.037550 127.0.0.1:5060 -> 127.0.0.1:5060
ACK sip:1001@127.0.0.1:5060 SIP/2.0.
From:  <sip:test@test>;tag=649721.
CSeq: 36999 ACK.
call-id: 790289.
Via: SIP/2.0/UDP d1ds04.telepointglobal.com:5060;branch=z9hG4bK845546;rport.
max-forwards: 70.
To:  <sip:1001@127.0.0.1:5060>.
.

**Comment by kirm** [comment]
1. SIP standard declares that names in sip messages are case insensitve (page 32).
2. Are you using  sip.js from npm? Because commit introduced  header names normalization (a216e8890c1b9b4652519e1bd431edc4f189cf41) is not in npm yet.

**Comment by kirm** [comment]
Using anything but 'call-id' as Call-ID header name is a application code bug. Commit a216e8890c1b9b4652519e1bd431edc4f189cf41 will prettify 'call-id' to 'Call-ID' in serailized message before sending it over network. I will push this commit to npm later today.
